In [2]:
import numpy as np

In [3]:
water_height = np.array([4.01, 4.03, 4.27, 4.29, 4.19,
                         4.15, 4.16, 4.23, 4.29, 4.19,
                         4.00, 4.22, 4.25, 4.19, 4.10,
                         4.14, 4.03, 4.23, 4.08, 14.20,
                         14.03, 11.20, 8.19, 6.18, 4.04,
                         4.08, 4.11, 4.23, 3.99, 4.23])

In [4]:
np.mean(water_height)

5.251

In [5]:
np.sort(water_height)

array([ 3.99,  4.  ,  4.01,  4.03,  4.03,  4.04,  4.08,  4.08,  4.1 ,
        4.11,  4.14,  4.15,  4.16,  4.19,  4.19,  4.19,  4.22,  4.23,
        4.23,  4.23,  4.23,  4.25,  4.27,  4.29,  4.29,  6.18,  8.19,
       11.2 , 14.03, 14.2 ])

In [6]:
np.median(water_height)

4.19

In [7]:
np.percentile(water_height, 75)

4.265

In [12]:
np.percentile(water_height, 85)

5.518499999999998

In [13]:
np.std(water_height)

2.784585367099861

## Calculate the mean of 2D array

Let's imagine a game of ring toss at a carnival. In this game, you have three different chances to get all three rings onto a stick. In our ring_toss array, each interior array (the arrays within the larger array) is one try, and each number is one ring toss. 1 represents a successful toss, 0 represents a fail.

In [16]:
ring_toss = np.array([[1, 0, 0], 
                          [0, 0, 1], 
                          [1, 0, 1]])

In [17]:
np.mean(ring_toss)

0.4444444444444444

To find the mean of each try(each row - axis 1)

In [19]:
np.mean(ring_toss, axis=1)

array([0.33333333, 0.33333333, 0.66666667])

To find the mean of all 1st tosses, 2nd tosses, i.e. the mean of each index position(or columns) - specify the axis 0.

In [20]:
np.mean(ring_toss, axis=0)

array([0.66666667, 0.        , 0.66666667])

#### Example 1

Five participants were asked to rate how drowsy the medication made them once a day for three days on a scale of one (least drowsy) to ten (most drowsy).

In [24]:
allergy_trials = np.array([[6, 1, 3, 8, 2], 
                           [2, 6, 3, 9, 8], 
                           [5, 2, 6, 9, 9]])

Use np.mean to find the average level of drowsiness across all the trials and save the result to the variable total_mean.

In [26]:
np.mean(allergy_trials)

5.266666666666667

In [27]:
#  find the average level of drowsiness across each day of the experiment
np.mean(allergy_trials, axis=1)

array([4. , 5.6, 6.2])

In [28]:
# find the average level of drowsiness across for each individual patient
np.mean(allergy_trials, axis=0)

array([4.33333333, 3.        , 4.        , 8.66666667, 6.33333333])

### Outliers

In [29]:
temps = np.array([86, 88, 94, 85, 97, 90, 87, 85, 94, 93, 92, 95, 98, 85, 94, 91, 97, 88, 87, 86, 99, 89, 89, 99, 88, 96, 93, 96, 85, 88, 191, 95, 96, 87, 99, 93, 90, 86, 87, 100, 187, 98, 101, 101, 96, 94, 96, 87, 86, 92, 98,94, 98, 90, 99, 96, 99, 86, 97, 98, 86, 90, 86, 94, 91, 88, 196, 195,93, 97, 199, 87, 87, 90, 90, 98, 88, 92, 97, 88, 85, 94, 88, 93, 198, 90, 91, 90, 92, 92])

In [30]:
np.sort(temps)

array([ 85,  85,  85,  85,  85,  86,  86,  86,  86,  86,  86,  86,  87,
        87,  87,  87,  87,  87,  87,  88,  88,  88,  88,  88,  88,  88,
        88,  89,  89,  90,  90,  90,  90,  90,  90,  90,  90,  91,  91,
        91,  92,  92,  92,  92,  92,  93,  93,  93,  93,  93,  94,  94,
        94,  94,  94,  94,  94,  95,  95,  96,  96,  96,  96,  96,  96,
        97,  97,  97,  97,  97,  98,  98,  98,  98,  98,  98,  99,  99,
        99,  99,  99, 100, 101, 101, 187, 191, 195, 196, 198, 199])

In [32]:
np.median(temps)

92.5

In [33]:
print(temps)

[ 86  88  94  85  97  90  87  85  94  93  92  95  98  85  94  91  97  88
  87  86  99  89  89  99  88  96  93  96  85  88 191  95  96  87  99  93
  90  86  87 100 187  98 101 101  96  94  96  87  86  92  98  94  98  90
  99  96  99  86  97  98  86  90  86  94  91  88 196 195  93  97 199  87
  87  90  90  98  88  92  97  88  85  94  88  93 198  90  91  90  92  92]


In [34]:
sorted = np.sort(temps)
print(sorted)

[ 85  85  85  85  85  86  86  86  86  86  86  86  87  87  87  87  87  87
  87  88  88  88  88  88  88  88  88  89  89  90  90  90  90  90  90  90
  90  91  91  91  92  92  92  92  92  93  93  93  93  93  94  94  94  94
  94  94  94  95  95  96  96  96  96  96  96  97  97  97  97  97  98  98
  98  98  98  98  99  99  99  99  99 100 101 101 187 191 195 196 198 199]


In [35]:
np.median(sorted)

92.5

### Example 2