# K Nearest Neighbour and Sklearn

KNN is an algorithm based on the idea that data points with similar atributes tend to fall into similar categories. When you plot a series of data points in a 2-D plot, data points with similar attributes will be close together and so will be classified as belonging to the same category.

The KNN algorithm draws a series of **decision boundaries** in order to classify the data points. 

![knn](../imgs/knn-1.png)

All machine learning models in sklearn are implemented as Python classes. These classes serve two purposes, they:

- implement the algorithms for learning and predicting
- store the information learned from the data.

Training the model is called **fitting** a model to the data, we use the sklearn `.fit()` method.

To predict the label of a new data point we use sklearn's `.predict()` method.

### Overview of using Sklearn to fit a KNN Classifier

In [ ]:
import pandas as pd
import numpy as np

from sklearn.neighbors import KNeighborsClassifier
from sklearn import datasets

# load the data
iris = datasets.load_iris()
X = iris.data # features, 2-D numpy array
y = iris.target # target, 1-D numpy array

# create the classifier
knn = KNeighborsClassifier(n_neighbors=6)

# fit the classifier to the training set
knn.fit(X, y)
KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski', 
                     metric_params=None, n_jobs=1, n_neighbors=6, weights='uniform');

**NOTE**  

Sklearn requires that:

- the features are homogenous, continuous values, e.g. all floats, as apposed to categorical data, e.g. male/female
- the features and labels/target must be a numpy array or pandas dataframe of the correct shape.
- there are no missing values in the dataset.
- each row be a sample or observation point, and each column be a variable or feature
- the target needs to be a single column with the same number of observations as the feature data. 

Common practce name the feature array `X` and response variable `y`.

The classifier is returned modified to fit our data. We can now pass it some unlabelled data. 

We call the `.predict()` method on the classifier and pass it the unlabelled data. Sklearn requires that the unlabelled data be an array, with the features in columns and the observations in rows.

For every observation in our unlabelled dataset, the classifier will return a prediction. Thus a unlabelled dataset of (3,4) - 3 observations/4 features, will return a 1-D array with 3 predictions, e.g. [1, 1, 0]

In [ ]:
X_new = []

# predicting on unlabelled data
y_prediction = knn.predict(X_new)

Using the house votes as an example.

In [1]:
import pandas as pd
import numpy as np

from sklearn.neighbors import KNeighborsClassifier

In [2]:
df = pd.read_csv('../data/house-votes-84.csv', header=None)
df.columns = ['party', 'infants', 'water', 'budget', 'physician', 'salvador',
       'religious', 'satellite', 'aid', 'missile', 'immigration', 'synfuels',
       'education', 'superfund', 'crime', 'duty_free_exports', 'eaa_rsa']
print(df.shape)
df.sample(10).T

(435, 17)


28        395       196       5         41   \
party              republican  democrat  democrat  democrat  democrat   
infants                     y         y         n         n         y   
water                       n         y         n         y         y   
budget                      n         y         y         y         y   
physician                   y         ?         n         n         n   
salvador                    y         n         n         y         n   
religious                   n         n         y         y         n   
satellite                   y         n         y         n         y   
aid                         y         y         y         n         y   
missile                     y         n         y         n         y   
immigration                 n         n         n         n         n   
synfuels                    n         y         y         n         n   
education                   y         ?         y         n         n   
superfund                   y         n         n         y         n   
crime                       y         n         y         y         n   
duty_free_exports           n         y         y         y         y   
eaa_rsa                     y         y         ?         y         ?   

                          347       20        43        321       81   
party              republican  democrat  democrat  democrat  democrat  
infants                     y         y         y         y         y  
water                       n         y         n         y         n  
budget                      n         y         y         y         y  
physician                   y         n         n         n         n  
salvador                    y         n         n         n         n  
religious                   y         ?         n         n         n  
satellite                   n         y         y         y         y  
aid                         n         y         y         y         y  
missile                     n         n         y         y         ?  
immigration                 y         n         n         y         y  
synfuels                    n         y         n         n         y  
education                   y         n         n         n         y  
superfund                   y         n         n         y         n  
crime                       y         n         n         n         y  
duty_free_exports           n         y         y         n         n  
eaa_rsa                     n         y         y         y         y

In [5]:
# replace '?' with 'n'
df.replace(to_replace='?', value='n', inplace=True)
df.sample(10).T

141         176       319         256         35   \
party              republican  republican  democrat  republican  republican   
infants                     n           n         y           n           n   
water                       n           n         n           n           y   
budget                      n           y         y           n           n   
physician                   y           y         n           y           y   
salvador                    y           n         n           y           y   
religious                   y           n         n           n           y   
satellite                   y           y         y           n           n   
aid                         y           y         y           n           n   
missile                     y           y         y           n           n   
immigration                 y           y         n           n           n   
synfuels                    n           n         n           n           n   
education                   y           n         n           y           y   
superfund                   y           n         n           n           y   
crime                       y           y         n           y           y   
duty_free_exports           n           y         y           n           n   
eaa_rsa                     y           y         n           n           n   

                        95          399       288       2           378  
party              democrat  republican  democrat  democrat  republican  
infants                   y           n         y         n           n  
water                     n           y         y         y           n  
budget                    y           n         y         y           n  
physician                 n           y         n         n           y  
salvador                  y           n         y         y           y  
religious                 y           y         y         y           y  
satellite                 n           n         n         n           n  
aid                       n           n         y         n           n  
missile                   n           n         n         n           n  
immigration               n           y         y         n           n  
synfuels                  y           n         y         y           n  
education                 n           y         n         n           y  
superfund                 n           y         y         y           y  
crime                     n           y         y         y           y  
duty_free_exports         y           n         y         n           n  
eaa_rsa                   y           n         y         n           y

Create arrays `X` and `y` for the features and the target variable. Note the use of `.drop()` to drop the target variable `party` from the feature array `X` as well as the use of the `.values` attribute to ensure `X` and `y` are NumPy arrays. Without using `.values`, `X` and `y` are a DataFrame and Series respectively; the scikit-learn API will accept them in this form also as long as they are of the right shape.

In [18]:
df_subset = df.drop('party', axis=1)
df_subset.head()

infants water budget physician salvador religious satellite aid missile  \
0       n     y      n         y        y         y         n   n       n   
1       n     y      n         y        y         y         n   n       n   
2       n     y      y         n        y         y         n   n       n   
3       n     y      y         n        n         y         n   n       n   
4       y     y      y         n        y         y         n   n       n   

  immigration synfuels education superfund crime duty_free_exports eaa_rsa  
0           y        n         y         y     y                 n       y  
1           n        n         y         y     y                 n       n  
2           n        y         n         y     y                 n       n  
3           n        y         n         y     n                 n       y  
4           n        y         n         y     y                 y       y

Our data set is a series of 'n' and 'y' strings, needs to be numerical for sklearn.

In [19]:
df_subset.replace(to_replace='n', value=0, inplace=True)
df_subset.replace(to_replace='y', value=1, inplace=True)
df_subset.head()

infants  water  budget  physician  salvador  religious  satellite  aid  \
0        0      1       0          1         1          1          0    0   
1        0      1       0          1         1          1          0    0   
2        0      1       1          0         1          1          0    0   
3        0      1       1          0         0          1          0    0   
4        1      1       1          0         1          1          0    0   

   missile  immigration  synfuels  education  superfund  crime  \
0        0            1         0          1          1      1   
1        0            0         0          1          1      1   
2        0            0         1          0          1      1   
3        0            0         1          0          1      0   
4        0            0         1          0          1      1   

   duty_free_exports  eaa_rsa  
0                  0        1  
1                  0        0  
2                  0        0  
3                  0        1  
4                  1        1

In [20]:
# Create arrays for the features and the response variable
y = df['party'].values
X = df_subset.values

In [21]:
# Create a k-NN classifier with 6 neighbors
knn = KNeighborsClassifier(n_neighbors=6)

# Fit the classifier to the data
knn.fit(X, y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=6, p=2,
           weights='uniform')

Our k-NN classifier with 6 neighbors has been fit to the data, it can be used to predict the labels of new data points.

In [24]:
# our unseen dataset with one observation
X_new = np.array([[0.113775, 0.177361, 0.34296, 0.928766, 0.055435, 0.280929, 0.117602,
    0.259329, 0.539605, 0.568447, 0.159349, 0.409809, 0.103259, 0.08121, 0.720823, 0.644942]])
X_new.shape

(1, 16)

In [25]:
y_pred = knn.predict(X_new)
print(y_pred)

['democrat']


Our model predicted 'democrat'. But how sure can we be in its accuracy? In other words, how can we measure the models performance?

The accuracy of our model is calculated as the **fraction of correct data points**, e.g. number of corrct predicions divided by the total number of data points.

This then leads to the next question, which data do we use to predict accuracy?

What we're interested in is our model's performance on new data, observations it has never seen before. It's thus common practice to split the data into two sets, a training set(used to train/fit the model) and a test set(used to make predicitions - this is a **labelled** test set). You can then compare the predictions to the labels. You then predict the accuracy of your predicions.

The process follows the following steps:

In [26]:
# import the 'train_test_split' function
from sklearn.model_selection import train_test_split

# use the function to randomly split our dataset into 4 arrays:
# - training data, test data, training labels and test labels
# test_size - what proportion of the dataset is used for the test set(default 75/25)
# random_state - sets a seed for the random number generator
# stratify - specify the list/array containing the labels, ensure that the labels 
# are ditributed between your train and test sets as they are in the original dataset.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, 
                                    random_state=21, stratify=y)

# instantiate our knn classifier
knn = KNeighborsClassifier(n_neighbors=6)

# fit the classifier to the data
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=6, p=2,
           weights='uniform')

In [28]:
# make the predixtions on the test data
y_pred = knn.predict(X_test)
y_pred[:10]

array(['democrat', 'republican', 'republican', 'democrat', 'democrat',
       'democrat', 'republican', 'republican', 'democrat', 'republican'],
      dtype=object)

Use the `.score()` method to test the accuracy of our model

In [30]:
print(X_test[:5])
print(y_test[:5])

[[1 1 0 0 0 0 0 1 1 0 1 0 0 0 1 0]
 [1 1 0 1 1 1 1 0 0 0 0 1 1 1 0 0]
 [0 0 1 1 1 1 0 0 0 1 0 1 1 1 1 1]
 [1 1 1 0 1 1 0 0 0 1 1 0 1 1 0 1]
 [1 0 1 0 0 0 1 1 1 0 1 0 0 0 1 0]]
['democrat' 'republican' 'republican' 'democrat' 'democrat']


In [29]:
knn.score(X_test, y_test)

0.9541984732824428

### Repeating our predictions using different values of 'k'

In general:

- as 'k' increases the decision boundary gets smoother, our model becomes less complex. You run the risk of **underfitting**, and our models performance is reduced.
- smaller 'k, means a more complex model and can lead to **overfitting**

We need to find the 'sweet' spot somewhere in the middle that gives the best results with the test set.

In [33]:
# instantiate our knn classifier
knn_1n = KNeighborsClassifier(n_neighbors=1)

# fit the classifier to the data
knn_1n.fit(X_train, y_train)

# score the model
knn_1n.score(X_test, y_test)

0.9618320610687023

In [34]:
# instantiate our knn classifier
knn_3n = KNeighborsClassifier(n_neighbors=3)

# fit the classifier to the data
knn_3n.fit(X_train, y_train)

# score the model
knn_3n.score(X_test, y_test)

0.9618320610687023

In [35]:
# instantiate our knn classifier
knn_9n = KNeighborsClassifier(n_neighbors=9)

# fit the classifier to the data
knn_9n.fit(X_train, y_train)

# score the model
knn_9n.score(X_test, y_test)

0.9465648854961832