In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from IPython.display import display
from scipy import sparse
%matplotlib inline
import matplotlib.pyplot as plt

from sklearn.datasets import load_iris
iris_dataset = load_iris()
print('Iris dataset keys:\n', iris_dataset.keys())

Iris dataset keys:
 dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [7]:
print(iris_dataset['DESCR'][:230] + '\n...')

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive attributes and the class
    
...


In [14]:
print('Target names:', iris_dataset['target_names'])


Target names: ['setosa' 'versicolor' 'virginica']


In [15]:
print('Feature names:', iris_dataset['feature_names'])


Feature names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [16]:
print('Type of data:', type(iris_dataset['data']))


Type of data: <class 'numpy.ndarray'>


In [17]:
print('Shape of data:', iris_dataset['data'].shape)

Shape of data: (150, 4)


In [20]:
print('First 5 rows of data:\n', iris_dataset['data'][:5])

First 5 rows of data:
 [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [21]:
print('Type of target:', type(iris_dataset['target']))

Type of target: <class 'numpy.ndarray'>


In [23]:
print('Type of target:', iris_dataset['target'].shape)

Type of target: (150,)


In [24]:
print('Target:\n', iris_dataset['target'])

Target:
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
