In [1]:
import numpy as np

Although numpy arrays support bool, int, float and string data types, a numpy array can be of only one data type.

In [2]:
# create an array filled with zeros, length 10
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [3]:
# create a 2D array filled with 1s - 3rows x 5 collumns
np.ones((3,5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [4]:
# create the same 2D array with a set value
np.full((4,4), 5.32)

array([[5.32, 5.32, 5.32, 5.32],
       [5.32, 5.32, 5.32, 5.32],
       [5.32, 5.32, 5.32, 5.32],
       [5.32, 5.32, 5.32, 5.32]])

In [5]:
# create a linear sequence - start at 0, upto(but NOT including) 100, incrementing by 10
np.arange(0,100,10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [15]:
# create a sequence of evenly spaced values
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [12]:
# create a 2D array of uniformaly distributed random numbers
np.random.random((3,3))

array([[0.91762184, 0.40253559, 0.50828706],
       [0.40950092, 0.81646072, 0.97539673],
       [0.25843347, 0.13127888, 0.31579489]])

In [13]:
# create a 2D 3x3 array of random ints between 0 and 10
np.random.randint(0,10,(3,3))

array([[9, 2, 2],
       [5, 6, 0],
       [7, 8, 8]])